version: '2'

services:
  middleman:
    image: gcr.io/bitnami-containers/middleman-boilerplate:latest
    ports:
      - 4567:4567
    volumes:
      - .:/app
    tty: true
    entrypoint: /app/scripts/entrypoint.sh
    command: middleman server
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 4567
      BITNAMI_CONTAINER_ORIGIN: bitnami_internal
